export const PHOT_AI_TOOLS =    {
    BACKGROUND_REMOVER: 'BACKGROUND_REMOVER',
    BACKGROUND_REPLACER: 'BACKGROUND_REPLACER',
    AI_PHOTO_ENHANCER: 'IMAGE_ENHANCER',
    IMAGE_UPSCALER: 'IMAGE_UPSCALER',
    AI_EXTENDER: 'AI_EXTENDER',
    PRODUCT_SHADOW: 'PRODUCT_SHADOW',
    BLUR_BACKGROUND: 'BACKGROUND_BLUR',
    IMAGE_LIGHT_FIX: 'IMAGE_LIGHT_FIX',
  }